"""Scrapy settings."""

BOT_NAME = "tunai_scrapers"

SPIDER_MODULES = ["tunai_scrapers.spiders"]
NEWSPIDER_MODULE = "tunai_scrapers.spiders"

USER_AGENT = "Mozilla/5.0 (compatible; TunaiParser/0.1; +https://example.com/bot)"

ROBOTSTXT_OBEY = True

TELNETCONSOLE_ENABLED = False
COOKIES_ENABLED = False

LOG_LEVEL = "INFO"

CONCURRENT_REQUESTS = 16
CONCURRENT_REQUESTS_PER_DOMAIN = 16
DOWNLOAD_DELAY = 0

AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 0.5
AUTOTHROTTLE_MAX_DELAY = 2.0
AUTOTHROTTLE_TARGET_CONCURRENCY = 6.0

REACTOR_THREADPOOL_MAXSIZE = 20

RETRY_ENABLED = True
RETRY_TIMES = 2

DNSCACHE_ENABLED = True
DNSCACHE_SIZE = 10000

HTTPCACHE_ENABLED = False
